name: CMake

on:
  push:
    branches: [ "development" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, 
  BUILD_TYPE: Release

jobs:
  build:
    runs-on:
      labels: development
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 8
      
    - name: generate benchmark data
      working-directory: ${{github.workspace}}/build
      run: ./krazymeans -b
      
    - name: Run
      working-directory: ${{github.workspace}}/build
      run: ./krazymeans -e -k 32 -s 1e-3 -t 25 -i example.kmd -o labels.kml
