name: CMake-benchmark

on:
  push:
    branches: [ "benchmark-gpu1" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, 
  BUILD_TYPE: Release

jobs:
  build:
    runs-on:
      labels: benchmark-gpu1
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 8

    - name: Print GPU model
      run: nvidia-smi --query-gpu=gpu_name --format=csv
      
    - name: Nsight-System profile
      working-directory: ${{github.workspace}}/build
      run: nsys profile ./krazymeans -b -k 32 -s 1e-3 -t 25 -i benchmark.kmd -o labels.kml
      
    - uses: actions/upload-artifact@v3
      with:
        name: Nsight-System profiling result
        path: ${{github.workspace}}/build/*.nsys-rep
              
